pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        mavenCentral()
    }
}

println('SETTINGS FILE: This is executed during the initialization phase')

rootProject.name = 'brote-api'

include ':apps-api-backend'
project(':apps-api-backend').projectDir = file('apps/api/backend')
project(':apps-api-backend').buildFileName = 'build.gradle'
project(":apps-api-backend").projectDir.mkdirs()

include ':backoffice'
project(':backoffice').projectDir = file('src/backoffice')
project(':backoffice').buildFileName = 'build.gradle'
project(":backoffice").projectDir.mkdirs()

include ':shared'
project(':shared').projectDir = file('src/shared')
project(':shared').buildFileName = 'build.gradle'
project(":shared").projectDir.mkdirs()